version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: enlacepro-mysql
    environment:
      MYSQL_DATABASE: enlacepro
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  mi-api-rest:
    image: nuhaila/enlace_pro:v3
    container_name: enlace_pro-container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/enlacepro?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    restart: always

volumes:
  mysql_data:
  