#==== Base de datos PROD ====
# La configuración de la base de datos se define en docker-compose.yml
# mediante variables de entorno

#=== JPA/hibernate ====
spring.jpa.hibernate.ddl-auto=validate 
spring.jpa.show-sql=false
    #indica a Hibernate que se usa MySQL para generar el SQL compatible con ese motor
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
    #cierra la sesión de JPA tras la capa de servicio(evita tener conexiones abiertas)
spring.jpa.open-in-view=false

    #solo mostrará errores graves en la consola 
logging.level.org.springframework=ERROR

#=== Desactivar Swagger en producción ====
springdoc.api-docs.enabled=false
springdoc.swagger-ui.enabled=false
