#==== Base de datos DEV ====

spring.datasource.url=jdbc:mysql://mysql:3306/enlacepro?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#=== JPA / Hibernate ====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hace que Spring espere a que Hibernate cree las tablas antes de ejecutar data.sql
spring.jpa.defer-datasource-initialization=true

# Dialecto para MySQL 8
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Ejecuta data.sql siempre
spring.sql.init.mode=always

# Cierra la sesión JPA al salir de la capa de servicio
spring.jpa.open-in-view=true
