spring.application.name=enlacePro
api.version = 1.0

# Configuración JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
    # No permitimos que toque el esquema que vamos a cargar desde shema.sql
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.error.include-message=always

# Perfil
spring.profiles.active=dev

# Seguridad
spring.security.user.name=user
spring.security.user.password=pass

