spring.application.name=enlacePro
api.version = 1.0


spring.jpa.show-sql=true
server.error.include-message=always

# Perfil
spring.profiles.active=dev

# ================== Seguridad ==================
spring.security.user.name=user
spring.security.user.password=pass

# ----- Seguridad -----
security.endpoint.alumnos=/alumnos/**
security.endpoint.idiomas=/idiomas/**

#URL del endpoint de autenticación en el servidor 
restclient.auth.baseurl=http://localhost:8081/auth/login
# URL del endpoint alumnos 
restclient.alumnos.baseurl=http://localhost:8080/alumnos

#URL de /idiomas
restclient.idiomas.baseurl=http://localhost:8080/idiomas

## Específicamente para el mapeo de URLs y vistas (muy útil para el 404)
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.servlet.view=DEBUG

# Internacionalización
spring.messages.encoding=UTF-8
# Ruta desde resources/nombre del fichero
spring.messages.basename=messages