@startuml Arquitectura
left to right direction

title Aquitectura de despliegue - Enlace Pro
'-----------------------------
'Cliente 
'-----------------------------

node PC as cliente <<device>>{
    node "Navegador Web" as navegador<<web browser>>
}
'-----------------------------
'Servidor 
'-----------------------------
node "Servidor de aplicación" as servidor <<device>>{
    node "Sistema Operativo" as SO <<SO>>{
        node  "JVM" as JVM <<Java Virtual Machine>>{
            node "Enlace Pro" as App <<Spring Boot>>
        }
    }
}
   
'-----------------------------
'Base de datos 
'-----------------------------
node H2 <<memory database>> as bbdd
'-----------------------------
'Relaciones
'-----------------------------
navegador -- App :**HTTP**:8080
App -- bbdd : **JDBC**:8082
@enduml 