@startuml nivel2_componentes

package "Enlace Pro"{
    package alumnos {
        component infraestructure as alumnoInfraesctructure
        component application as alumnoApp
        component domain as alumnoDomain
    }
    package common{
        component infraestructure as commonInfraestructure
        component domain as commonDomain

        alumnos .right.> common: use
    }
    
}
alumnoInfraesctructure ..> alumnoApp : use
alumnoApp ..> alumnoDomain : use


@enduml