@startuml diagrama_contexto
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

Person(rol_administrador, "Administrador", "Gestiona y mantiene el sistema")
Person(rol_usuario, "Usuario", "Cliente registrado en el sistema")

System(systemAlias, "EnlacePro", "Plataforma central de gestión y adaptación lingüística para Aulas de Enlace")

SystemDb_Ext(database, "MySQL", "Base de datos relacional externa")

Rel(rol_administrador, systemAlias, "Gestiona usuarios e idiomas")
Rel(rol_usuario, systemAlias, "Consulta y gestiona contenidos")
Rel(systemAlias, database, "Almacena y recupera información", "JDBC/MySQL")

SHOW_LEGEND()

@enduml