@startuml diagrama_de_contenedores
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(rol_administrador, "Administrador", "Gestiona y mantiene el sistema")
Person(rol_usuario, "Usuario", "Cliente registrado en el sistema")

System_Boundary(c1, "EnlacePro App") {
    Container(monolito, "Aplicación Web Monolítica", "Spring Boot + Thymeleaf", "Controladores REST, lógica de negocio, vistas y acceso a datos")
}

SystemDb_Ext(database, "MySQL", "Base de datos relacional externa")

Rel(rol_administrador, monolito, "Usa desde navegador", "HTTPS")
Rel(rol_usuario, monolito, "Usa desde navegador", "HTTPS")
Rel(monolito, database, "Lectura y escritura de datos", "JDBC/MySQL")

SHOW_LEGEND()

@enduml