@startuml Casos de uso - Enlace Pro
left to right direction
skinparam actorStyle awesome

actor Usuario
actor Alumno
actor "Profesor de Enlace" as profesor
actor "Padre/Tutor legar" as padreTutor
actor Director

rectangle "Enlace Pro"{
    usecase "Acceder a contenido traducido" as uc1
    usecase "Acceder a contenido adaptado por nivel" as uc2
    usecase "Subir contenido y versiones adaptadas" as uc3
    usecase "Gestionar nivel del alumno" as uc4
    usecase "Enviar comunicados/notas multilingües" as uc5
    usecase "Consultar informes/notas traducidas" as uc6
    usecase "Gestión de alumnos, profesores e idiomas" as uc7
}

Usuario <|-- Alumno
Usuario <|-- profesor
Usuario <|-- padreTutor
Usuario <|-- Director
Alumno -- uc1
Alumno -- uc2 
profesor -- uc3
profesor -- uc4
profesor --uc5
padreTutor -- uc6
Director --uc7

@enduml
